name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init project
        uses: actions/checkout@v2
      - name: Init node.js
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Install Sass
        run: npm install -D sass-loader node-sass
      - name: Install Vue Router
        run: npm install vue-router
      - name: Install Bootstrap
        run: npm install vue bootstrap-vue bootstrap
      - name: Building the project
        run: npm run build
      - name: Run Eslint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}